In [4]:
import pandas as pd

Bayut_DF = pd.read_csv("bayut_selling_properties.csv")
Transactions_DF = pd.read_csv("Transactions.csv")
RealEstate24_DF = pd.read_csv("uae_real_estate_2024.csv")

In [5]:
Bayut_DF.describe(include='all')

,price,price_category,type,beds,baths,address,furnishing,completion_status,post_date,average_rent,...,total_parking_spaces,total_floors,total_building_area_sqft,elevators,area_name,city,country,Latitude,Longitude,purpose
count,4.138100e+04,41381,41381,41381.000000,41381.000000,41381,41381,41381,41381,4.138100e+04,...,41381.000000,41381.000000,41381.000000,41381.000000,41381,41381,41381,41363.000000,41363.000000,41381
unique,NaN,3,9,NaN,NaN,3899,2,2,457,NaN,...,NaN,NaN,NaN,NaN,275,9,1,NaN,NaN,1
top,NaN,Medium,Apartment,NaN,NaN,"Al Yasmeen, Ajman",Unfurnished,Ready,2024-04-17,NaN,...,NaN,NaN,NaN,NaN,Jumeirah Village Circle (JVC),Dubai,UAE,NaN,NaN,For Sale
freq,NaN,13964,28998,NaN,NaN,361,31966,24904,1484,NaN,...,NaN,NaN,NaN,NaN,2477,28809,41381,NaN,NaN,41381
mean,3.788624e+06,NaN,NaN,2.190957,3.007540,NaN,NaN,NaN,NaN,9.292880e+04,...,172.559073,13.212126,142.931273,2.304463,NaN,NaN,NaN,25.037851,55.158407,NaN
std,8.482870e+06,NaN,NaN,1.567855,1.785553,NaN,NaN,NaN,NaN,2.503703e+05,...,353.899074,20.298365,248.719849,4.440953,NaN,NaN,NaN,0.437348,0.513871,NaN
min,0.000000e+00,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,15.175847,43.351928,NaN
25%,1.100000e+06,NaN,NaN,1.000000,2.000000,NaN,NaN,NaN,NaN,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,25.026710,55.135252,NaN
50%,2.000000e+06,NaN,NaN,2.000000,3.000000,NaN,NaN,NaN,NaN,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,25.078641,55.245999,NaN
75%,3.600000e+06,NaN,NaN,3.000000,4.000000,NaN,NaN,NaN,NaN,1.243790e+05,...,198.000000,22.000000,211.000000,4.000000,NaN,NaN,NaN,25.189427,55.307913,NaN
max,4.825000e+08,NaN,NaN,11.000000,11.000000,NaN,NaN,NaN,NaN,2.807952e+07,...,2929.000000,89.000000,997.000000,42.000000,NaN,NaN,NaN,25.797689,56.361294,NaN

In [6]:
Bayut_DF.info()

<class 'pandas.DataFrame'>
RangeIndex: 41381 entries, 0 to 41380
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   price                     41381 non-null  int64
 1   price_category            41381 non-null  str
 2   type                      41381 non-null  str
 3   beds                      41381 non-null  int64
 4   baths                     41381 non-null  int64
 5   address                   41381 non-null  str
 6   furnishing                41381 non-null  str
 7   completion_status         41381 non-null  str
 8   post_date                 41381 non-null  str
 9   average_rent              41381 non-null  int64
 10  building_name             41381 non-null  str
 11  year_of_completion        41381 non-null  int64
 12  total_parking_spaces      41381 non-null  int64
 13  total_floors              41381 non-null  int64
 14  total_building_area_sqft  41381 non-null  int64
 15  elevators                 41381 non-null  int64
 16  area_name                 41381 non-null  str
 17  city                      41381 non-null  str
 18  country                   41381 non-null  str
 19  Latitude                  41363 non-null  float64
 20  Longitude                 41363 non-null  float64
 21  purpose                   41381 non-null  str
dtypes: float64(2), int64(9), str(11)
memory usage: 12.2 MB

In [7]:
Bayut_DF.isnull().sum()

price                        0
price_category               0
type                         0
beds                         0
baths                        0
address                      0
furnishing                   0
completion_status            0
post_date                    0
average_rent                 0
building_name                0
year_of_completion           0
total_parking_spaces         0
total_floors                 0
total_building_area_sqft     0
elevators                    0
area_name                    0
city                         0
country                      0
Latitude                    18
Longitude                   18
purpose                      0
dtype: int64

In [8]:
Bayut_DF.head()

,price,price_category,type,beds,baths,address,furnishing,completion_status,post_date,average_rent,...,total_parking_spaces,total_floors,total_building_area_sqft,elevators,area_name,city,country,Latitude,Longitude,purpose
0,1450000,Medium,Apartment,1,2,"The Bay, Business Bay, Dubai",Furnished,Ready,2024-04-15,0,...,0,0,0,0,Business Bay,Dubai,UAE,25.189427,55.264819,For Sale
1,6600000,High,Townhouse,5,5,"Brookfield, DAMAC Hills, Dubai",Unfurnished,Ready,2024-04-15,0,...,0,0,0,0,DAMAC Hills,Dubai,UAE,25.028148,55.264246,For Sale
2,4825000,High,Apartment,2,3,"Vida Residence Downtown, Downtown Dubai, Dubai",Unfurnished,Ready,2024-04-18,288929,...,510,56,1,11,Downtown Dubai,Dubai,UAE,25.186684,55.274705,For Sale
3,980000,Average,Apartment,3,3,"Building 39, Al Reef Downtown, Al Reef, Abu Dhabi",Unfurnished,Ready,2024-01-03,73384,...,0,0,0,0,Al Reef,Abu Dhabi,UAE,24.466437,54.656891,For Sale
4,2499999,Medium,Townhouse,3,4,"Nima, The Valley, Dubai",Furnished,Off-Plan,2024-02-28,0,...,0,0,0,0,The Valley,Dubai,UAE,25.019221,55.447201,For Sale

In [9]:
Transactions_DF.describe(include='all')

,transaction_id,procedure_id,trans_group_id,trans_group_ar,trans_group_en,procedure_name_ar,procedure_name_en,instance_date,property_type_id,property_type_ar,...,rooms_en,has_parking,procedure_area,actual_worth,meter_sale_price,rent_value,meter_rent_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3
count,1047965,1.047965e+06,1.047965e+06,1047965,1047965,1047965,1047965,1047960,1.047965e+06,1047965,...,799030,1.047965e+06,1.047965e+06,1.044160e+06,1.047965e+06,3.429900e+04,3.430200e+04,1.046813e+06,1.046813e+06,1.046813e+06
unique,1047965,NaN,NaN,3,3,50,50,6961,NaN,4,...,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,1-11-2001-165,NaN,NaN,مبايعات,Sales,بيع,Sell,03-10-2013,NaN,وحدة,...,1 B/R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,787892,787892,348060,348060,4026,NaN,721070,...,259994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,5.870308e+01,1.282417e+00,NaN,NaN,NaN,NaN,NaN,3.022047e+00,NaN,...,NaN,5.983988e-01,1.599632e+03,2.557483e+06,1.348875e+04,1.416090e+06,2.102467e+04,1.285542e+00,1.193500e+00,1.559524e-01
std,NaN,9.111008e+01,5.207231e-01,NaN,NaN,NaN,NaN,NaN,7.345969e-01,NaN,...,NaN,4.902223e-01,3.558513e+05,5.968448e+06,1.246936e+05,1.733329e+06,2.934084e+05,3.301961e+00,5.187964e-01,6.239861e-01
min,NaN,4.000000e+00,1.000000e+00,NaN,NaN,NaN,NaN,NaN,1.000000e+00,NaN,...,NaN,0.000000e+00,5.000000e-02,1.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,NaN,1.100000e+01,1.000000e+00,NaN,NaN,NaN,NaN,NaN,3.000000e+00,NaN,...,NaN,0.000000e+00,7.228000e+01,6.804000e+05,6.210910e+03,5.984930e+05,4.940000e+03,1.000000e+00,1.000000e+00,0.000000e+00
50%,NaN,1.300000e+01,1.000000e+00,NaN,NaN,NaN,NaN,NaN,3.000000e+00,NaN,...,NaN,1.000000e+00,1.224700e+02,1.245500e+06,9.334010e+03,1.001000e+06,7.152500e+03,1.000000e+00,1.000000e+00,0.000000e+00
75%,NaN,1.020000e+02,1.000000e+00,NaN,NaN,NaN,NaN,NaN,3.000000e+00,NaN,...,NaN,1.000000e+00,2.555700e+02,2.285490e+06,1.404738e+04,1.760000e+06,1.007075e+04,1.000000e+00,1.000000e+00,0.000000e+00
max,NaN,8.610000e+02,3.000000e+00,NaN,NaN,NaN,NaN,NaN,4.000000e+00,NaN,...,NaN,1.000000e+00,3.421034e+08,9.997125e+07,3.499578e+07,8.500000e+07,1.109416e+07,7.030000e+02,5.100000e+01,1.700000e+01

In [10]:
Transactions_DF.info()

<class 'pandas.DataFrame'>
RangeIndex: 1047965 entries, 0 to 1047964
Data columns (total 46 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   transaction_id        1047965 non-null  str
 1   procedure_id          1047965 non-null  int64
 2   trans_group_id        1047965 non-null  int64
 3   trans_group_ar        1047965 non-null  str
 4   trans_group_en        1047965 non-null  str
 5   procedure_name_ar     1047965 non-null  str
 6   procedure_name_en     1047965 non-null  str
 7   instance_date         1047960 non-null  str
 8   property_type_id      1047965 non-null  int64
 9   property_type_ar      1047965 non-null  str
 10  property_type_en      1047965 non-null  str
 11  property_sub_type_id  807819 non-null   float64
 12  property_sub_type_ar  807819 non-null   str
 13  property_sub_type_en  807819 non-null   str
 14  property_usage_ar     1047965 non-null  str
 15  property_usage_en     1047965 non-null  str
 16  reg_type_id           1047965 non-null  int64
 17  reg_type_ar           1047965 non-null  str
 18  reg_type_en           1047965 non-null  str
 19  area_id               1047965 non-null  int64
 20  area_name_ar          1047965 non-null  str
 21  area_name_en          1047965 non-null  str
 22  building_name_ar      719800 non-null   str
 23  building_name_en      721070 non-null   str
 24  project_number        657372 non-null   float64
 25  project_name_ar       657372 non-null   str
 26  project_name_en       657372 non-null   str
 27  master_project_en     864153 non-null   str
 28  master_project_ar     864106 non-null   str
 29  nearest_landmark_ar   922241 non-null   str
 30  nearest_landmark_en   922241 non-null   str
 31  nearest_metro_ar      811141 non-null   str
 32  nearest_metro_en      811141 non-null   str
 33  nearest_mall_ar       805823 non-null   str
 34  nearest_mall_en       805823 non-null   str
 35  rooms_ar              799030 non-null   str
 36  rooms_en              799030 non-null   str
 37  has_parking           1047965 non-null  int64
 38  procedure_area        1047965 non-null  float64
 39  actual_worth          1044160 non-null  float64
 40  meter_sale_price      1047965 non-null  float64
 41  rent_value            34299 non-null    float64
 42  meter_rent_price      34302 non-null    float64
 43  no_of_parties_role_1  1046813 non-null  float64
 44  no_of_parties_role_2  1046813 non-null  float64
 45  no_of_parties_role_3  1046813 non-null  float64
dtypes: float64(10), int64(6), str(30)
memory usage: 798.5 MB

In [11]:
Transactions_DF.isnull().sum()

transaction_id                0
procedure_id                  0
trans_group_id                0
trans_group_ar                0
trans_group_en                0
procedure_name_ar             0
procedure_name_en             0
instance_date                 5
property_type_id              0
property_type_ar              0
property_type_en              0
property_sub_type_id     240146
property_sub_type_ar     240146
property_sub_type_en     240146
property_usage_ar             0
property_usage_en             0
reg_type_id                   0
reg_type_ar                   0
reg_type_en                   0
area_id                       0
area_name_ar                  0
area_name_en                  0
building_name_ar         328165
building_name_en         326895
project_number           390593
project_name_ar          390593
project_name_en          390593
master_project_en        183812
master_project_ar        183859
nearest_landmark_ar      125724
nearest_landmark_en      125724
nearest_metro_ar         236824
nearest_metro_en         236824
nearest_mall_ar          242142
nearest_mall_en          242142
rooms_ar                 248935
rooms_en                 248935
has_parking                   0
procedure_area                0
actual_worth               3805
meter_sale_price              0
rent_value              1013666
meter_rent_price        1013663
no_of_parties_role_1       1152
no_of_parties_role_2       1152
no_of_parties_role_3       1152
dtype: int64

In [12]:
Transactions_DF.head()

,transaction_id,procedure_id,trans_group_id,trans_group_ar,trans_group_en,procedure_name_ar,procedure_name_en,instance_date,property_type_id,property_type_ar,...,rooms_en,has_parking,procedure_area,actual_worth,meter_sale_price,rent_value,meter_rent_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3
0,1-11-2001-165,11,1,مبايعات,Sales,بيع,Sell,24-02-2001,1,أرض,...,NaN,0,1393.55,1350000.0,968.75,NaN,NaN,1.0,1.0,0.0
1,3-9-2004-223,9,3,هبات,Gifts,هبه,Grant,13-12-2004,4,فيلا,...,NaN,0,1728.00,2790000.0,1614.58,NaN,NaN,1.0,1.0,0.0
2,2-13-1996-119,13,2,رهون,Mortgages,تسجيل رهن,Mortgage Registration,12-03-2001,1,أرض,...,NaN,0,929.03,20000000.0,21527.83,NaN,NaN,1.0,1.0,0.0
3,2-14-2005-222,14,2,رهون,Mortgages,تعديل رهن,Modify Mortgage,20-09-2005,2,مبنى,...,NaN,0,2673.28,25000000.0,9351.81,NaN,NaN,1.0,1.0,0.0
4,3-9-2012-874,9,3,هبات,Gifts,هبه,Grant,11-10-2012,4,فيلا,...,NaN,0,1541.17,9000000.0,5839.72,NaN,NaN,1.0,1.0,0.0

In [13]:
RealEstate24_DF.describe(include='all')

,title,displayAddress,bathrooms,bedrooms,addedOn,type,price,verified,priceDuration,sizeMin,furnishing,description
count,5058,5058,4938,4935,5058,5058,5.058000e+03,5058,5058,5058,5056,5057
unique,5002,1886,9,9,4927,1,NaN,2,1,2516,3,4940
top,Waterfront | Emaar | Luxury | PP 80/20,"Hayyan, Sharjah",2,1,2024-07-29T14:12:37Z,Residential for Sale,NaN,True,sell,3014 sqft,NO,*Luxury residential complex with a 5% down pay...
freq,3,40,1209,1265,7,5058,NaN,3271,5058,46,3630,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,5.050924e+06,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,1.000928e+07,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+05,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,1.200000e+06,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,2.350000e+06,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,4.499375e+06,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,1.990000e+08,NaN,NaN,NaN,NaN,NaN

In [14]:
RealEstate24_DF.isnull().sum()

title               0
displayAddress      0
bathrooms         120
bedrooms          123
addedOn             0
type                0
price               0
verified            0
priceDuration       0
sizeMin             0
furnishing          2
description         1
dtype: int64

In [15]:
RealEstate24_DF.info()

<class 'pandas.DataFrame'>
RangeIndex: 5058 entries, 0 to 5057
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           5058 non-null   str
 1   displayAddress  5058 non-null   str
 2   bathrooms       4938 non-null   str
 3   bedrooms        4935 non-null   str
 4   addedOn         5058 non-null   str
 5   type            5058 non-null   str
 6   price           5058 non-null   int64
 7   verified        5058 non-null   bool
 8   priceDuration   5058 non-null   str
 9   sizeMin         5058 non-null   str
 10  furnishing      5056 non-null   str
 11  description     5057 non-null   str
dtypes: bool(1), int64(1), str(10)
memory usage: 7.4 MB

In [16]:
RealEstate24_DF.head()

,title,displayAddress,bathrooms,bedrooms,addedOn,type,price,verified,priceDuration,sizeMin,furnishing,description
0,Great ROI I High Floor I Creek View,"Binghatti Canal, Business Bay, Dubai",3,2,2024-08-14T12:02:53Z,Residential for Sale,2500000,True,sell,1323 sqft,NO,MNA Properties is delighted to offer this apar...
1,Full Sea View | Beach Life | Brand New Residence,"La Vie, Jumeirah Beach Residence, Dubai",3,2,2024-08-13T05:45:16Z,Residential for Sale,7200000,True,sell,1410 sqft,YES,"Apartment for sale in La Vie, Jumeirah Beach R..."
2,Green Belt | Corner Unit | Spacious Plot,"La Rosa 6, Villanova, Dubai Land, Dubai",3,4,2024-08-14T06:24:28Z,Residential for Sale,3600000,True,sell,2324 sqft,NO,Treo Homes is very pleased to be bringing to t...
3,2BR+Study | Near Pool and Park | Private,"Springs 15, The Springs, Dubai",3,2,2024-08-15T06:07:22Z,Residential for Sale,2999999,True,sell,1647 sqft,NO,2 Bedrooms + Study | Near Pool &amp; Park | Pr...
4,Vacant | Well Maintained | Area Expert,"Noor Townhouses, Town Square, Dubai",3,3,2024-08-09T08:28:59Z,Residential for Sale,2449999,True,sell,2105 sqft,NO,-Type 1\n-3 Bed+Maid\n-Close To Amenities\n-BU...

#### Choosing Bayut_DF for further analysis as it has more data and less null values compared to the other two datasets

In [17]:
Bayut_DF.describe(include=['object']).T

C:\Users\InsuranceMarket.ae\AppData\Local\Temp\ipykernel_8336\3934191184.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  Bayut_DF.describe(include=['object']).T

                   count unique                            top   freq
price_category     41381      3                         Medium  13964
type               41381      9                      Apartment  28998
address            41381   3899              Al Yasmeen, Ajman    361
furnishing         41381      2                    Unfurnished  31966
completion_status  41381      2                          Ready  24904
post_date          41381    457                     2024-04-17   1484
building_name      41381   1700                        Unknown  23491
area_name          41381    275  Jumeirah Village Circle (JVC)   2477
city               41381      9                          Dubai  28809
country            41381      1                            UAE  41381
purpose            41381      1                       For Sale  41381

In [18]:
Bayut_DF.describe().T

,count,mean,std,min,25%,50%,75%,max
price,41381.0,3.788624e+06,8.482870e+06,0.000000,1.100000e+06,2.000000e+06,3.600000e+06,4.825000e+08
beds,41381.0,2.190957e+00,1.567855e+00,0.000000,1.000000e+00,2.000000e+00,3.000000e+00,1.100000e+01
baths,41381.0,3.007540e+00,1.785553e+00,0.000000,2.000000e+00,3.000000e+00,4.000000e+00,1.100000e+01
average_rent,41381.0,9.292880e+04,2.503703e+05,0.000000,0.000000e+00,0.000000e+00,1.243790e+05,2.807952e+07
year_of_completion,41381.0,6.811125e+02,9.538869e+02,0.000000,0.000000e+00,0.000000e+00,2.012000e+03,2.024000e+03
total_parking_spaces,41381.0,1.725591e+02,3.538991e+02,0.000000,0.000000e+00,0.000000e+00,1.980000e+02,2.929000e+03
total_floors,41381.0,1.321213e+01,2.029837e+01,0.000000,0.000000e+00,0.000000e+00,2.200000e+01,8.900000e+01
total_building_area_sqft,41381.0,1.429313e+02,2.487198e+02,0.000000,0.000000e+00,0.000000e+00,2.110000e+02,9.970000e+02
elevators,41381.0,2.304463e+00,4.440953e+00,0.000000,0.000000e+00,0.000000e+00,4.000000e+00,4.200000e+01
Latitude,41363.0,2.503785e+01,4.373482e-01,15.175847,2.502671e+01,2.507864e+01,2.518943e+01,2.579769e+01
Longitude,41363.0,5.515841e+01,5.138713e-01,43.351928,5.513525e+01,5.524600e+01,5.530791e+01,5.636129e+01

In [19]:
Bayut_DF.isnull().sum()

price                        0
price_category               0
type                         0
beds                         0
baths                        0
address                      0
furnishing                   0
completion_status            0
post_date                    0
average_rent                 0
building_name                0
year_of_completion           0
total_parking_spaces         0
total_floors                 0
total_building_area_sqft     0
elevators                    0
area_name                    0
city                         0
country                      0
Latitude                    18
Longitude                   18
purpose                      0
dtype: int64

In [20]:
print(Bayut_DF.head(1))

     price price_category       type  beds  baths  \
0  1450000         Medium  Apartment     1      2

                        address furnishing completion_status   post_date  \
0  The Bay, Business Bay, Dubai  Furnished             Ready  2024-04-15

   average_rent  ... total_parking_spaces  total_floors  \
0             0  ...                    0             0

   total_building_area_sqft  elevators     area_name   city country  \
0                         0          0  Business Bay  Dubai     UAE

    Latitude  Longitude   purpose
0  25.189427  55.264819  For Sale

[1 rows x 22 columns]

In [21]:
# Columns to inspect
cols_to_check = [
    'total_building_area_sqft', 
    'total_floors', 
    'elevators', 
    'average_rent', 
    'beds', 
    'baths', 
    'total_parking_spaces',
    'price'
]

# Count zeros in each column
zero_counts = {col: (Bayut_DF[col] == 0).sum() for col in cols_to_check}

print("Zero value counts in Bayut dataset:")
for col, count in zero_counts.items():
    total = Bayut_DF[col].shape[0]
    pct = (count / total) * 100
    print(f"{col:30} : {count:6} zeros ({pct:.2f}%)")

Zero value counts in Bayut dataset:
total_building_area_sqft       :  23609 zeros (57.05%)
total_floors                   :  23492 zeros (56.77%)
elevators                      :  28289 zeros (68.36%)
average_rent                   :  20762 zeros (50.17%)
beds                           :   4627 zeros (11.18%)
baths                          :    131 zeros (0.32%)
total_parking_spaces           :  28366 zeros (68.55%)
price                          :     16 zeros (0.04%)

In [22]:
percentiles = [95, 99, 99.5, 99.9, 100]
price_percentiles = Bayut_DF['price'].describe(percentiles=[p/100 for p in percentiles])

# Also show the max
print("Price percentiles:")
for p in percentiles:
    value = Bayut_DF['price'].quantile(p/100)
    print(f"{p:5.1f}th percentile: {value:,.0f} AED")

print(f"\nMax price: {Bayut_DF['price'].max():,.0f} AED")

Price percentiles:
 95.0th percentile: 11,500,000 AED
 99.0th percentile: 35,960,000 AED
 99.5th percentile: 49,999,999 AED
 99.9th percentile: 95,000,000 AED
100.0th percentile: 482,500,000 AED

Max price: 482,500,000 AED

In [23]:
cap = 50_000_000   # or 95_000_000
least_cap = 0
Bayut_DF = Bayut_DF[(Bayut_DF['price'] > least_cap) & (Bayut_DF['price'] <= cap)]
print(Bayut_DF['price'].describe(percentiles=[.95, .99, .995, .999]))

count    4.116800e+04
mean     3.394042e+06
std      4.880480e+06
min      9.500000e+04
95%      1.091500e+07
99%      2.750000e+07
99.5%    3.651650e+07
99.9%    4.600000e+07
max      5.000000e+07
Name: price, dtype: float64

In [24]:
# Use original Bayut_DF (before cleaning) to see patterns
zero_beds = Bayut_DF[Bayut_DF['beds'] == 0]
print(zero_beds['type'].value_counts())
print(Bayut_DF['type'].unique())

type
Apartment               4367
Residential Plot         131
Hotel Apartment          127
Residential Building       2
Name: count, dtype: int64
<ArrowStringArray>
[           'Apartment',            'Townhouse',     'Residential Plot',
                'Villa',            'Penthouse',      'Hotel Apartment',
       'Villa Compound', 'Residential Building',    'Residential Floor']
Length: 9, dtype: str

In [25]:
# Count of zero beds per type
zero_beds_by_type = Bayut_DF[Bayut_DF['beds'] == 0]['type'].value_counts()
print("Zero beds distribution by type:")
print(zero_beds_by_type)

# Also show total count per type for context
total_by_type = Bayut_DF['type'].value_counts()
print("\nTotal rows per type:")
print(total_by_type)

Zero beds distribution by type:
type
Apartment               4367
Residential Plot         131
Hotel Apartment          127
Residential Building       2
Name: count, dtype: int64

Total rows per type:
type
Apartment               28947
Villa                    7262
Townhouse                3412
Residential Plot          939
Penthouse                 296
Hotel Apartment           193
Residential Building       76
Villa Compound             38
Residential Floor           5
Name: count, dtype: int64

In [26]:
import numpy as np

df = Bayut_DF.copy()
drop_cols = ['total_building_area_sqft', 'total_floors', 'elevators',
    'average_rent', 'total_parking_spaces',
    'price_category', 'purpose', 'country', 'post_date',
    'building_name', 'address', 'year_of_completion']
df.drop(columns=drop_cols, inplace=True, errors='ignore')

df.dropna(subset=['Latitude', 'Longitude'], inplace=True)

median_baths = df[df['baths'] > 0]['baths'].median()
df['baths'] = df['baths'].replace(0, median_baths)


#    - Keep zero beds for Residential Plot, Hotel Apartment, Residential Building
#    - Remove zero beds for any other type (especially Apartment)
valid_zero_bed_types = ['Residential Plot', 'Hotel Apartment', 'Residential Building']
df = df[~((df['beds'] == 0) & (~df['type'].isin(valid_zero_bed_types)))]

categorical_cols = ['type', 'furnishing', 'area_name', 'completion_status']
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print("Data cleaning complete. Final shape:", df.shape)

Data cleaning complete. Final shape: (36783, 275)

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import xgboost as xgb
import numpy as np

X = df.drop('price', axis=1)
y = df['price']

# Ensure all columns numeric
X = X.select_dtypes(include=[np.number])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = xgb.XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=6, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"RMSE: {rmse:,.0f} AED")
print(f"R²: {r2:.3f}")

RMSE: 2,518,157 AED
R²: 0.720

In [28]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error
import numpy as np

# Predict on test set
y_pred = model.predict(X_test)

# Metrics
mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

# Adjusted R²
n = X_test.shape[0]
p = X_test.shape[1]
adj_r2 = 1 - (1-r2) * (n-1)/(n-p-1)

print("=== Model Performance ===")
print(f"RMSE: {rmse:,.0f} AED")
print(f"MAE: {mae:,.0f} AED")
print(f"MAPE: {mape:.2%}")
print(f"R²: {r2:.3f}")
print(f"Adjusted R²: {adj_r2:.3f}")

=== Model Performance ===
RMSE: 2,518,157 AED
MAE: 1,107,801 AED
MAPE: 32.09%
R²: 0.720
Adjusted R²: 0.720

In [29]:
#!pip install optuna --quiet    # Uncomment this line if optuna is not installed
import optuna
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import make_scorer
import numpy as np
import xgboost as xgb

# Get your data (X, y) from memory. Do NOT split again.

def objective(trial):
    # Define a comprehensive search space
    param = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=50),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'gamma': trial.suggest_float('gamma', 1e-8, 5.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'random_state': 42,
        'n_jobs': -1
    }

    # Inner CV
    kfold = KFold(n_splits=3, shuffle=True, random_state=42)
    score = cross_val_score(
        xgb.XGBRegressor(**param), 
        X, y, 
        cv=kfold, 
        scoring='neg_root_mean_squared_error', 
        n_jobs=-1
    ).mean()
    return -score

# Run the optimization (30 trials is a good start)
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=30, show_progress_bar=True)

# Train the final model on all data
best_params = study.best_params
final_model = xgb.XGBRegressor(**best_params, random_state=42)
final_model.fit(X, y)

[I 2026-04-29 23:34:34,253] A new study created in memory with name: no-name-764d8f3e-2fe5-4055-a0c2-2805154da2a6

  0%|          | 0/30 [00:00<?, ?it/s]

[I 2026-04-29 23:34:38,591] Trial 0 finished with value: 2934237.5 and parameters: {'n_estimators': 700, 'max_depth': 3, 'learning_rate': 0.034151557553295554, 'subsample': 0.7151837124026375, 'colsample_bytree': 0.9661641265389576, 'gamma': 0.0002586251671769741, 'reg_lambda': 3.453313745471026e-07, 'reg_alpha': 0.02655487251126998, 'min_child_weight': 9}. Best is trial 0 with value: 2934237.5.
[I 2026-04-29 23:34:44,138] Trial 1 finished with value: 2773970.8333333335 and parameters: {'n_estimators': 800, 'max_depth': 11, 'learning_rate': 0.02065478311666304, 'subsample': 0.6076916411662572, 'colsample_bytree': 0.8254043559590947, 'gamma': 4.876478573954752e-08, 'reg_lambda': 0.9454403612694574, 'reg_alpha': 0.00014724039191649603, 'min_child_weight': 10}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:34:46,874] Trial 2 finished with value: 2875674.6666666665 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.017301584616394527, 'subsample': 0.8288798201113856, 'colsample_bytree': 0.7942006682570418, 'gamma': 9.670065023391038e-05, 'reg_lambda': 0.0011206219550199397, 'reg_alpha': 2.5310872770850135e-05, 'min_child_weight': 2}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:34:48,451] Trial 3 finished with value: 2859003.8333333335 and parameters: {'n_estimators': 750, 'max_depth': 4, 'learning_rate': 0.022380201757811257, 'subsample': 0.8444978995394379, 'colsample_bytree': 0.8148796921786194, 'gamma': 0.00010443212621765328, 'reg_lambda': 1.0517413019474259e-08, 'reg_alpha': 4.0710642988366407e-07, 'min_child_weight': 9}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:34:49,568] Trial 4 finished with value: 2893795.9166666665 and parameters: {'n_estimators': 150, 'max_depth': 11, 'learning_rate': 0.011263838957595165, 'subsample': 0.7752495461511747, 'colsample_bytree': 0.8244280577054408, 'gamma': 0.004674958822422601, 'reg_lambda': 2.388900630294014e-06, 'reg_alpha': 0.0004624029328336351, 'min_child_weight': 1}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:34:54,369] Trial 5 finished with value: 2852068.1666666665 and parameters: {'n_estimators': 1000, 'max_depth': 11, 'learning_rate': 0.04253471213345615, 'subsample': 0.9770399679189082, 'colsample_bytree': 0.9731178318399716, 'gamma': 0.011725169889032602, 'reg_lambda': 0.0003118949495590578, 'reg_alpha': 1.910672212119793e-08, 'min_child_weight': 3}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:34:55,888] Trial 6 finished with value: 3016859.5 and parameters: {'n_estimators': 650, 'max_depth': 4, 'learning_rate': 0.014415726891244152, 'subsample': 0.6122451388834124, 'colsample_bytree': 0.7113201704680341, 'gamma': 0.12069598207901205, 'reg_lambda': 8.08221922940913e-05, 'reg_alpha': 9.56080688482889, 'min_child_weight': 6}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:34:56,773] Trial 7 finished with value: 2843343.8333333335 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.048196091206804945, 'subsample': 0.6704439522902159, 'colsample_bytree': 0.619860575128145, 'gamma': 0.00013008019478650206, 'reg_lambda': 0.023608716450171333, 'reg_alpha': 7.840678598899093, 'min_child_weight': 7}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:34:58,922] Trial 8 finished with value: 3056492.0 and parameters: {'n_estimators': 800, 'max_depth': 4, 'learning_rate': 0.00602539100199385, 'subsample': 0.69665842663547, 'colsample_bytree': 0.8903635617203892, 'gamma': 2.9381866521223138e-05, 'reg_lambda': 0.00011698394356461656, 'reg_alpha': 1.5470478117510057e-05, 'min_child_weight': 5}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:35:01,436] Trial 9 finished with value: 2780545.6666666665 and parameters: {'n_estimators': 400, 'max_depth': 12, 'learning_rate': 0.028278372377183333, 'subsample': 0.976651472407329, 'colsample_bytree': 0.6626232222151646, 'gamma': 3.369617075166639e-07, 'reg_lambda': 0.002538862592136564, 'reg_alpha': 7.031138245562179e-05, 'min_child_weight': 4}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:35:04,480] Trial 10 finished with value: 2847770.0833333335 and parameters: {'n_estimators': 1000, 'max_depth': 8, 'learning_rate': 0.1704652207030594, 'subsample': 0.6036742009835288, 'colsample_bytree': 0.8920036598223179, 'gamma': 2.1936890661474576e-08, 'reg_lambda': 2.638209346726367, 'reg_alpha': 0.011998103018654381, 'min_child_weight': 10}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:35:06,041] Trial 11 finished with value: 2798440.3333333335 and parameters: {'n_estimators': 450, 'max_depth': 12, 'learning_rate': 0.10142015118633099, 'subsample': 0.9980875387639899, 'colsample_bytree': 0.6041181626831102, 'gamma': 1.709029904312705e-08, 'reg_lambda': 5.353832657675746, 'reg_alpha': 0.00013467079687834948, 'min_child_weight': 4}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:35:06,467] Trial 12 finished with value: 2792465.5833333335 and parameters: {'n_estimators': 100, 'max_depth': 9, 'learning_rate': 0.07816903674178145, 'subsample': 0.9144528364120272, 'colsample_bytree': 0.7088396472671129, 'gamma': 6.834117415895352e-07, 'reg_lambda': 0.06600315845975788, 'reg_alpha': 0.004131722113523553, 'min_child_weight': 7}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:35:08,761] Trial 13 finished with value: 2820923.0833333335 and parameters: {'n_estimators': 550, 'max_depth': 10, 'learning_rate': 0.0071154257443322285, 'subsample': 0.9056653940686904, 'colsample_bytree': 0.7153803321397951, 'gamma': 1.7360279219774525e-06, 'reg_lambda': 0.13254232070574087, 'reg_alpha': 2.8219540079830452e-06, 'min_child_weight': 4}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:35:12,924] Trial 14 finished with value: 2804999.75 and parameters: {'n_estimators': 850, 'max_depth': 12, 'learning_rate': 0.029268830700366337, 'subsample': 0.7517826441019012, 'colsample_bytree': 0.7593796029916995, 'gamma': 3.916913970671701e-07, 'reg_lambda': 0.005029007036777524, 'reg_alpha': 0.20367704388531488, 'min_child_weight': 7}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:35:13,616] Trial 15 finished with value: 2786090.0 and parameters: {'n_estimators': 250, 'max_depth': 7, 'learning_rate': 0.06919411558199644, 'subsample': 0.8962718765843319, 'colsample_bytree': 0.6446525203263413, 'gamma': 1.5916954141061157e-07, 'reg_lambda': 0.5755200500883592, 'reg_alpha': 0.0006050954822790604, 'min_child_weight': 5}. Best is trial 1 with value: 2773970.8333333335.
[I 2026-04-29 23:35:15,899] Trial 16 finished with value: 2771844.0833333335 and parameters: {'n_estimators': 550, 'max_depth': 10, 'learning_rate': 0.009570917547908247, 'subsample': 0.9503916752043983, 'colsample_bytree': 0.885226071450352, 'gamma': 1.0899706452067948e-05, 'reg_lambda': 9.817834499349926e-06, 'reg_alpha': 2.8211406651219617e-07, 'min_child_weight': 10}. Best is trial 16 with value: 2771844.0833333335.
[I 2026-04-29 23:35:18,007] Trial 17 finished with value: 2780079.1666666665 and parameters: {'n_estimators': 550, 'max_depth': 9, 'learning_rate': 0.010706183349999454, 'subsample': 0.648843692015259, 'colsample_bytree': 0.8738441434390021, 'gamma': 9.395654220841721e-06, 'reg_lambda': 4.762610319144491e-06, 'reg_alpha': 1.0124701580320188e-08, 'min_child_weight': 10}. Best is trial 16 with value: 2771844.0833333335.
[I 2026-04-29 23:35:20,661] Trial 18 finished with value: 2803156.1666666665 and parameters: {'n_estimators': 900, 'max_depth': 7, 'learning_rate': 0.005190499663008208, 'subsample': 0.8566356558395389, 'colsample_bytree': 0.9419229231607043, 'gamma': 5.5404200280636416e-06, 'reg_lambda': 1.091154947235221e-05, 'reg_alpha': 4.0030503521362526e-07, 'min_child_weight': 9}. Best is trial 16 with value: 2771844.0833333335.
[I 2026-04-29 23:35:23,280] Trial 19 finished with value: 2770350.6666666665 and parameters: {'n_estimators': 600, 'max_depth': 10, 'learning_rate': 0.009517363195211516, 'subsample': 0.7960142483413242, 'colsample_bytree': 0.8484198542853701, 'gamma': 2.9485766408908822, 'reg_lambda': 1.0318128801714768e-07, 'reg_alpha': 1.9725308361001172e-07, 'min_child_weight': 8}. Best is trial 19 with value: 2770350.6666666665.
[I 2026-04-29 23:35:26,109] Trial 20 finished with value: 2773883.0 and parameters: {'n_estimators': 600, 'max_depth': 9, 'learning_rate': 0.008210168187142632, 'subsample': 0.8028360835015136, 'colsample_bytree': 0.8620394121826048, 'gamma': 1.9493922691192738, 'reg_lambda': 3.256053092861254e-08, 'reg_alpha': 2.3436133718600443e-07, 'min_child_weight': 8}. Best is trial 19 with value: 2770350.6666666665.
[I 2026-04-29 23:35:29,780] Trial 21 finished with value: 2771483.9166666665 and parameters: {'n_estimators': 600, 'max_depth': 9, 'learning_rate': 0.009364573764833895, 'subsample': 0.7923768163058656, 'colsample_bytree': 0.8610759807807932, 'gamma': 1.7858547362898358, 'reg_lambda': 5.2794257608223815e-08, 'reg_alpha': 1.567147007840727e-07, 'min_child_weight': 8}. Best is trial 19 with value: 2770350.6666666665.
[I 2026-04-29 23:35:32,931] Trial 22 finished with value: 2773517.6666666665 and parameters: {'n_estimators': 500, 'max_depth': 10, 'learning_rate': 0.009552594672955824, 'subsample': 0.7545448305612861, 'colsample_bytree': 0.9253806127185463, 'gamma': 2.3818497813491475, 'reg_lambda': 2.3169937691273007e-07, 'reg_alpha': 8.098133963603797e-08, 'min_child_weight': 8}. Best is trial 19 with value: 2770350.6666666665.
[I 2026-04-29 23:35:35,786] Trial 23 finished with value: 2767647.3333333335 and parameters: {'n_estimators': 650, 'max_depth': 8, 'learning_rate': 0.01366199494248085, 'subsample': 0.7893245302789471, 'colsample_bytree': 0.8509710312193912, 'gamma': 0.27342674331711775, 'reg_lambda': 2.3795159248002934e-07, 'reg_alpha': 2.8841321385892088e-06, 'min_child_weight': 8}. Best is trial 23 with value: 2767647.3333333335.
[I 2026-04-29 23:35:38,638] Trial 24 finished with value: 2769214.8333333335 and parameters: {'n_estimators': 650, 'max_depth': 8, 'learning_rate': 0.013052067899393843, 'subsample': 0.7978792432340504, 'colsample_bytree': 0.7741011239535232, 'gamma': 0.24581721042499777, 'reg_lambda': 4.1926022409511045e-07, 'reg_alpha': 3.6365776758057524e-06, 'min_child_weight': 8}. Best is trial 23 with value: 2767647.3333333335.
[I 2026-04-29 23:35:41,668] Trial 25 finished with value: 2770435.4166666665 and parameters: {'n_estimators': 700, 'max_depth': 8, 'learning_rate': 0.01440663251644518, 'subsample': 0.7278442023273841, 'colsample_bytree': 0.7709946025395514, 'gamma': 0.28950110568628873, 'reg_lambda': 7.724020474531238e-07, 'reg_alpha': 3.448542333839508e-06, 'min_child_weight': 6}. Best is trial 23 with value: 2767647.3333333335.
[I 2026-04-29 23:35:43,977] Trial 26 finished with value: 2837396.6666666665 and parameters: {'n_estimators': 650, 'max_depth': 6, 'learning_rate': 0.014098389048630146, 'subsample': 0.8172623231522586, 'colsample_bytree': 0.7465271599881896, 'gamma': 0.1336728267158615, 'reg_lambda': 6.135800828083977e-08, 'reg_alpha': 2.458487210904291e-06, 'min_child_weight': 8}. Best is trial 23 with value: 2767647.3333333335.
[I 2026-04-29 23:35:45,829] Trial 27 finished with value: 2770876.75 and parameters: {'n_estimators': 450, 'max_depth': 8, 'learning_rate': 0.02021623635824626, 'subsample': 0.8620235084593646, 'colsample_bytree': 0.8408591461378705, 'gamma': 0.010326319140124616, 'reg_lambda': 9.73642287211935e-07, 'reg_alpha': 8.851327702607707e-06, 'min_child_weight': 7}. Best is trial 23 with value: 2767647.3333333335.
[I 2026-04-29 23:35:49,273] Trial 28 finished with value: 2854374.6666666665 and parameters: {'n_estimators': 900, 'max_depth': 7, 'learning_rate': 0.23821335102091556, 'subsample': 0.7527391837092703, 'colsample_bytree': 0.7957136937202813, 'gamma': 0.5842831873134327, 'reg_lambda': 1.3924785005900182e-07, 'reg_alpha': 1.062057964125627e-06, 'min_child_weight': 9}. Best is trial 23 with value: 2767647.3333333335.
[I 2026-04-29 23:35:51,930] Trial 29 finished with value: 2843473.1666666665 and parameters: {'n_estimators': 700, 'max_depth': 6, 'learning_rate': 0.006560788107697926, 'subsample': 0.7265229744984794, 'colsample_bytree': 0.9233720531422981, 'gamma': 0.030883126262644195, 'reg_lambda': 2.5330602327651897e-05, 'reg_alpha': 5.254535081365181e-08, 'min_child_weight': 6}. Best is trial 23 with value: 2767647.3333333335.

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8509710312193912, device=None,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, feature_types=None, feature_weights=None,
             gamma=0.27342674331711775, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01366199494248085,
             max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=8, max_leaves=None,
             min_child_weight=8, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=650, n_jobs=None,
             num_parallel_tree=None, ...)

In [30]:
# Best parameters from Optuna (trial 24)
best_params = {
    'n_estimators': 900,
    'max_depth': 8,
    'learning_rate': 0.008915313449781819,
    'subsample': 0.670382096294307,
    'colsample_bytree': 0.909067971774471,
    'gamma': 2.5343647814948075e-05,
    'reg_lambda': 4.0970419139887015e-06,
    'reg_alpha': 5.797304343487931e-07,
    'min_child_weight': 7,
    'random_state': 42,
    'n_jobs': -1
}

# Now train on the full training set (X_train, y_train) using best_params
final_model = xgb.XGBRegressor(**best_params)
final_model.fit(X_train, y_train)

# Predict on the same test set you used earlier
y_pred_tuned = final_model.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

rmse_tuned = np.sqrt(mean_squared_error(y_test, y_pred_tuned))
r2_tuned = r2_score(y_test, y_pred_tuned)

print(f"Baseline   - RMSE: 2,518,157 AED | R²: 0.720")
print(f"Optuna Tuned - RMSE: {rmse_tuned:,.0f} AED | R²: {r2_tuned:.3f}")

Baseline   - RMSE: 2,518,157 AED | R²: 0.720
Optuna Tuned - RMSE: 2,523,316 AED | R²: 0.719

In [31]:
df

,price,beds,baths,city,Latitude,Longitude,type_Hotel Apartment,type_Penthouse,type_Residential Building,type_Residential Floor,...,area_name_Umm Suqeim,area_name_Wadi Al Safa 2,area_name_Wasit Suburb,area_name_Wasl Gate,area_name_World Trade Centre,area_name_Yas Island,area_name_Yasmin Village,area_name_Za'abeel,area_name_Zayed City,completion_status_Ready
0,1450000,1,2,Dubai,25.189427,55.264819,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,6600000,5,5,Dubai,25.028148,55.264246,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,4825000,2,3,Dubai,25.186684,55.274705,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,980000,3,3,Abu Dhabi,24.466437,54.656891,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,2499999,3,4,Dubai,25.019221,55.447201,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41373,1280000,1,1,Dubai,25.177246,55.307913,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41374,920000,1,2,Dubai,25.055945,55.207465,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41375,3850000,4,4,Dubai,25.065152,55.322788,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41376,7100000,2,2,Dubai,25.118088,55.134201,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41378,3188900,2,2,Dubai,25.164759,55.218728,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False

In [32]:
Bayut_DF

,price,price_category,type,beds,baths,address,furnishing,completion_status,post_date,average_rent,...,total_parking_spaces,total_floors,total_building_area_sqft,elevators,area_name,city,country,Latitude,Longitude,purpose
0,1450000,Medium,Apartment,1,2,"The Bay, Business Bay, Dubai",Furnished,Ready,2024-04-15,0,...,0,0,0,0,Business Bay,Dubai,UAE,25.189427,55.264819,For Sale
1,6600000,High,Townhouse,5,5,"Brookfield, DAMAC Hills, Dubai",Unfurnished,Ready,2024-04-15,0,...,0,0,0,0,DAMAC Hills,Dubai,UAE,25.028148,55.264246,For Sale
2,4825000,High,Apartment,2,3,"Vida Residence Downtown, Downtown Dubai, Dubai",Unfurnished,Ready,2024-04-18,288929,...,510,56,1,11,Downtown Dubai,Dubai,UAE,25.186684,55.274705,For Sale
3,980000,Average,Apartment,3,3,"Building 39, Al Reef Downtown, Al Reef, Abu Dhabi",Unfurnished,Ready,2024-01-03,73384,...,0,0,0,0,Al Reef,Abu Dhabi,UAE,24.466437,54.656891,For Sale
4,2499999,Medium,Townhouse,3,4,"Nima, The Valley, Dubai",Furnished,Off-Plan,2024-02-28,0,...,0,0,0,0,The Valley,Dubai,UAE,25.019221,55.447201,For Sale
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41376,7100000,High,Apartment,2,2,"Serenia Living Tower 1, Serenia Living, Palm J...",Unfurnished,Off-Plan,2024-02-13,0,...,625,19,384,6,Palm Jumeirah,Dubai,UAE,25.118088,55.134201,For Sale
41377,928200,Average,Apartment,0,1,"Upper House East, Upper House, Jumeirah Lake T...",Unfurnished,Off-Plan,2024-02-13,0,...,401,40,890,7,Jumeirah Lake Towers (JLT),Dubai,UAE,25.069063,55.141166,For Sale
41378,3188900,High,Apartment,2,2,"Jadeel Building 3, Jadeel, Madinat Jumeirah Li...",Unfurnished,Off-Plan,2024-02-09,0,...,0,0,0,0,Umm Suqeim,Dubai,UAE,25.164759,55.218728,For Sale
41379,670000,Average,Apartment,0,1,"Luxor by Imtiaz, JVC District 14, Jumeirah Vil...",Unfurnished,Off-Plan,2024-03-05,0,...,0,0,0,0,Jumeirah Village Circle (JVC),Dubai,UAE,25.055945,55.207465,For Sale
41380,650000,Average,Apartment,0,1,"LOCI Residences, JVC District 14, Jumeirah Vil...",Unfurnished,Off-Plan,2024-01-30,0,...,111,8,168,2,Jumeirah Village Circle (JVC),Dubai,UAE,25.055945,55.207465,For Sale

In [33]:
import pandas as pd
import numpy as np

def haversine(lat1, lon1, lat2, lon2):
    """Calculate the great-circle distance in kilometers."""
    R = 6371.0
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    return R * c

# --- Your 40+ Points of Interest (Lat, Lon) ---
pois = {
    # 1. Iconic Landmarks & Attractions
    'burj_khalifa': (25.197197, 55.274376),
    'dubai_mall': (25.197090, 55.278620),
    'burj_al_arab': (25.141196, 55.185454),
    'palm_jumeirah': (25.116383, 55.139559),
    'sheikh_zayed_mosque': (24.412743, 54.474444),
    'louvre_abu_dhabi': (24.533676, 54.398437),
    'ferrari_world': (24.484454, 54.606971),
    'museum_of_future': (25.219223, 55.283609),
    'dubai_frame': (25.235241, 55.301825),
    'the_view_palm': (25.112782, 55.134610),
    'dubai_miracle_garden': (25.058247, 55.241297),
    'global_village': (25.044235, 55.222128),
    'ain_dubai': (25.068429, 55.130301),
    'al_fahidi_historic': (25.264057, 55.298240),
    'al_seef': (25.269226, 55.294002),
    'jumeirah_mosque': (25.235383, 55.265474),
    'jebel_hafeet': (24.208064, 55.769036),
    'al_ain_oasis': (24.214680, 55.771054),
    'sharjah_islamic_museum': (25.362105, 55.391296),
    'rak_national_museum': (25.792943, 55.946385),
    'fujairah_fort': (25.129519, 56.332801),

    # 2. Major Shopping Malls
    'mall_of_emirates': (25.118055, 55.200558),
    'dubai_marina_mall': (25.077202, 55.138627),
    'yas_mall': (24.489998, 54.609653),
    'marina_mall_abudhabi': (24.516067, 54.378895),
    'al_wahda_mall': (24.482346, 54.374337),
    'city_centre_sharjah': (25.319778, 55.388287),

    # 3. Business Hubs & Transport
    'dxb_airport': (25.253859, 55.365406),
    'auh_airport': (24.433056, 54.651111),
    'difc': (25.214170, 55.281390),

    # 4. Beaches & Outdoor Spaces
    'jbr_beach': (25.082100, 55.139500),
    'kite_beach': (25.220881, 55.247368),
    'abudhabi_corniche': (24.490281, 54.361358),
    'al_mamzar_beach': (25.301958, 55.335899),

    # 5. Green Spaces & Recreational Areas
    'zabeel_park': (25.236417, 55.304775),
    'safa_park': (25.207472, 55.248348),
    'mushrif_park': (25.222098, 55.565946),
    'jumeirah_beach_park': (25.228752, 55.250213),
    'barsha_pond_park': (25.118020, 55.201168),
    'umm_emarat_park': (24.460397, 54.391140),
    'ajman_beach': (25.411977, 55.443830),
    'al_zorah_nature': (25.384752, 55.952226),
}

# Add distance features to your cleaned dataframe
for name, (lat_poi, lon_poi) in pois.items():
    try:
        df[f'dist_to_{name}_km'] = haversine(df['Latitude'], df['Longitude'], lat_poi, lon_poi)
    except Exception as e:
        print(f'Error with {name}: {e}')
        print('Skipping...')
        continue

# Verify new columns
print([col for col in df.columns if col.startswith('dist_to_')])

['dist_to_burj_khalifa_km', 'dist_to_dubai_mall_km', 'dist_to_burj_al_arab_km', 'dist_to_palm_jumeirah_km', 'dist_to_sheikh_zayed_mosque_km', 'dist_to_louvre_abu_dhabi_km', 'dist_to_ferrari_world_km', 'dist_to_museum_of_future_km', 'dist_to_dubai_frame_km', 'dist_to_the_view_palm_km', 'dist_to_dubai_miracle_garden_km', 'dist_to_global_village_km', 'dist_to_ain_dubai_km', 'dist_to_al_fahidi_historic_km', 'dist_to_al_seef_km', 'dist_to_jumeirah_mosque_km', 'dist_to_jebel_hafeet_km', 'dist_to_al_ain_oasis_km', 'dist_to_sharjah_islamic_museum_km', 'dist_to_rak_national_museum_km', 'dist_to_fujairah_fort_km', 'dist_to_mall_of_emirates_km', 'dist_to_dubai_marina_mall_km', 'dist_to_yas_mall_km', 'dist_to_marina_mall_abudhabi_km', 'dist_to_al_wahda_mall_km', 'dist_to_city_centre_sharjah_km', 'dist_to_dxb_airport_km', 'dist_to_auh_airport_km', 'dist_to_difc_km', 'dist_to_jbr_beach_km', 'dist_to_kite_beach_km', 'dist_to_abudhabi_corniche_km', 'dist_to_al_mamzar_beach_km', 'dist_to_zabeel_park_km', 'dist_to_safa_park_km', 'dist_to_mushrif_park_km', 'dist_to_jumeirah_beach_park_km', 'dist_to_barsha_pond_park_km', 'dist_to_umm_emarat_park_km', 'dist_to_ajman_beach_km', 'dist_to_al_zorah_nature_km']

In [34]:
# Ensure that all features are numeric
feature_cols = [col for col in df.columns if col not in ['price', 'Latitude', 'Longitude']]
X = df[feature_cols]
y = df['price']

# Create train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# A quick check for non-numeric leftovers. If any remain, print them.
non_numeric = X.select_dtypes(exclude=[np.number]).columns
if len(non_numeric) > 0:
    print(f'Non-numeric columns found: {list(non_numeric)}')
    # For safety, we'll drop them; ideally, your dummy encoding step in cleaning handled these.
    X.drop(columns=non_numeric, inplace=True)

Non-numeric columns found: ['city', 'type_Hotel Apartment', 'type_Penthouse', 'type_Residential Building', 'type_Residential Floor', 'type_Residential Plot', 'type_Townhouse', 'type_Villa', 'type_Villa Compound', 'furnishing_Unfurnished', 'area_name_Abu Shagara', 'area_name_Address Fujairah Beach Resort', 'area_name_Ajman Downtown', 'area_name_Ajman Free Zone', 'area_name_Ajman Uptown', 'area_name_Al Abar', 'area_name_Al Alia', 'area_name_Al Ameera Village', 'area_name_Al Amerah', 'area_name_Al Azra', 'area_name_Al Badaa', 'area_name_Al Bahia', 'area_name_Al Barari', 'area_name_Al Barsha', 'area_name_Al Bateen', 'area_name_Al Bustan', 'area_name_Al Danah', 'area_name_Al Darari', 'area_name_Al Dhaid', 'area_name_Al Falaj', 'area_name_Al Fayha', 'area_name_Al Fisht', "area_name_Al Fou'ah", 'area_name_Al Furjan', 'area_name_Al Ghadeer', 'area_name_Al Ghafia', 'area_name_Al Gharayen', 'area_name_Al Gharb', 'area_name_Al Ghubaiba', 'area_name_Al Goaz', 'area_name_Al Gurm', 'area_name_Al Hamidiyah', 'area_name_Al Hamra Village', 'area_name_Al Helio', 'area_name_Al Hudayriat Island', 'area_name_Al Jaddaf', 'area_name_Al Jazzat', 'area_name_Al Jubail Island', 'area_name_Al Jurf', 'area_name_Al Karama', 'area_name_Al Khan', 'area_name_Al Khawaneej', 'area_name_Al Khezamia', 'area_name_Al Majaz', 'area_name_Al Mamzar', 'area_name_Al Manama', 'area_name_Al Manara', 'area_name_Al Marjan Island', 'area_name_Al Maryah Island', 'area_name_Al Matar', 'area_name_Al Mina', 'area_name_Al Mizhar', 'area_name_Al Mowaihat', 'area_name_Al Muntazah', 'area_name_Al Muroor', 'area_name_Al Musalla', 'area_name_Al Mushrif', 'area_name_Al Nabba', 'area_name_Al Nahda (Sharjah)', 'area_name_Al Nahyan', 'area_name_Al Nakhil', 'area_name_Al Nekhailat', 'area_name_Al Noaf', 'area_name_Al Nuaimiya', 'area_name_Al Qarayen', 'area_name_Al Qasba', 'area_name_Al Qasimia', 'area_name_Al Quoz', 'area_name_Al Qurm', 'area_name_Al Qusais', 'area_name_Al Raha Beach', 'area_name_Al Raha Gardens', 'area_name_Al Rahba', 'area_name_Al Rahmaniya', 'area_name_Al Ramaqiya', 'area_name_Al Ramla', 'area_name_Al Ramtha', 'area_name_Al Rashidiya', 'area_name_Al Rawda', 'area_name_Al Reef', 'area_name_Al Reem Island', 'area_name_Al Rifa', 'area_name_Al Riqaibah', 'area_name_Al Rumaila', 'area_name_Al Sabkha', 'area_name_Al Safa', 'area_name_Al Salam City', 'area_name_Al Salamah', 'area_name_Al Samha', 'area_name_Al Sarouj', 'area_name_Al Satwa', 'area_name_Al Sawan', 'area_name_Al Sehma', 'area_name_Al Shamkha', 'area_name_Al Shawamekh', 'area_name_Al Sufouh', 'area_name_Al Suyoh', 'area_name_Al Taawun', 'area_name_Al Tai', 'area_name_Al Tallah 1', 'area_name_Al Tallah 2', 'area_name_Al Tay East', 'area_name_Al Tiwayya', 'area_name_Al Twar', 'area_name_Al Warqaa', 'area_name_Al Wasl', 'area_name_Al Yahar', 'area_name_Al Yarmook', 'area_name_Al Yash', 'area_name_Al Yasmeen', 'area_name_Al Zahir', 'area_name_Al Zahya', 'area_name_Al Zorah', 'area_name_Al Zubair', 'area_name_Aljada', 'area_name_Arabian Ranches', 'area_name_Arabian Ranches 2', 'area_name_Arabian Ranches 3', 'area_name_Arjan', 'area_name_Asharij', 'area_name_Baniyas', 'area_name_Barashi', 'area_name_Barsha Heights (Tecom)', 'area_name_Bluewaters Island', 'area_name_Bu Tina', 'area_name_Bukadra', 'area_name_Bur Dubai', 'area_name_Business Bay', 'area_name_City of Arabia', 'area_name_Corniche Ajman', 'area_name_Culture Village', 'area_name_DAMAC Hills', 'area_name_DAMAC Hills 2 (Akoya by DAMAC)', 'area_name_DAMAC Lagoons', 'area_name_DIFC', 'area_name_Dafan Al Khor', 'area_name_Dafan Al Nakheel', 'area_name_Dasman', 'area_name_Deira', 'area_name_Discovery Gardens', 'area_name_Downtown Dubai', 'area_name_Dubai Creek Harbour', 'area_name_Dubai Design District', 'area_name_Dubai Festival City', 'area_name_Dubai Harbour', 'area_name_Dubai Hills Estate', 'area_name_Dubai Industrial City', 'area_name_Dubai Internet City', 'area_name_Dubai Investment Park (DIP)', 'area_name_Dubai Islands', 'area_name_Dubai Marina', 'area_name_Dubai Maritime City', 'area_name_Dubai Media City', 'area_name_Dubai Production City (IMPZ)', 'area_name_Dubai Residence Complex', 'area_name_Dubai Science Park', 'area_name_Dubai Silicon Oasis (DSO)', 'area_name_Dubai South', 'area_name_Dubai Sports City', 'area_name_Dubai Studio City', 'area_name_Dubai Waterfront', 'area_name_Dubailand', 'area_name_Emirates City', 'area_name_Emirates Hills', 'area_name_Expo City', 'area_name_Falaj Al Mualla', 'area_name_Falcon City of Wonders', 'area_name_Garden City', 'area_name_Ghantoot', 'area_name_Green Community', 'area_name_Halwan Suburb', 'area_name_Hoshi', 'area_name_Hydra Village', 'area_name_Industrial Area', 'area_name_International City', 'area_name_Jebel Ali', 'area_name_Jumeirah', 'area_name_Jumeirah Beach Residence (JBR)', 'area_name_Jumeirah Golf Estates', 'area_name_Jumeirah Heights', 'area_name_Jumeirah Islands', 'area_name_Jumeirah Lake Towers (JLT)', 'area_name_Jumeirah Park', 'area_name_Jumeirah Village Circle (JVC)', 'area_name_Jumeirah Village Triangle (JVT)', 'area_name_Khalifa City', 'area_name_Khor Fakkan', 'area_name_Living Legends', 'area_name_Liwan', 'area_name_Liwan 2', 'area_name_Liwara 1', 'area_name_Madinat Al Riyadh', 'area_name_Madinat Zayed', 'area_name_Majan', 'area_name_Marina Village', 'area_name_Masdar City', 'area_name_Masfoot', 'area_name_Meydan City', 'area_name_Mina Al Arab', 'area_name_Mina Rashid', 'area_name_Mirdif', 'area_name_Mohammed Bin Rashid City', 'area_name_Mohammed Bin Zayed City', 'area_name_Motor City', 'area_name_Mudon', 'area_name_Muhaisnah', 'area_name_Muwaileh', 'area_name_Muwailih Commercial', 'area_name_Muzairah', 'area_name_Nad Al Hamar', 'area_name_Nad Al Sheba', 'area_name_Nareel Island', 'area_name_Nurai Island', 'area_name_Palm Jebel Ali', 'area_name_Palm Jumeirah', 'area_name_Pearl Jumeirah', 'area_name_Rabdan', 'area_name_Ramhan Island', 'area_name_Ras Al Khor', 'area_name_Rawdhat Abu Dhabi', 'area_name_Reem', 'area_name_Remraam', 'area_name_Rodhat Al Qrt', 'area_name_Saadiyat Island', 'area_name_Serena', 'area_name_Shakhbout City', 'area_name_Sharjah Garden City', 'area_name_Sharjah Waterfront City', 'area_name_Sharqan', 'area_name_Sheikh Maktoum Bin Rashid Street', 'area_name_Sheikh Zayed Road', 'area_name_Sobha Hartland', 'area_name_The Acres', 'area_name_The Cove Rotana Resort', 'area_name_The Greens', 'area_name_The Hills', 'area_name_The Lakes', 'area_name_The Marina', 'area_name_The Meadows', 'area_name_The Oasis by Emaar', 'area_name_The Springs', 'area_name_The Sustainable City', 'area_name_The Valley', 'area_name_The Views', 'area_name_The Villa', 'area_name_The World Islands', 'area_name_Tilal Al Ghaf', 'area_name_Tilal City', 'area_name_Town Square', 'area_name_Umm Al Quwain Marina', 'area_name_Umm Suqeim', 'area_name_Wadi Al Safa 2', 'area_name_Wasit Suburb', 'area_name_Wasl Gate', 'area_name_World Trade Centre', 'area_name_Yas Island', 'area_name_Yasmin Village', "area_name_Za'abeel", 'area_name_Zayed City', 'completion_status_Ready']

In [35]:
# Identify and drop any non-numeric columns
non_numeric_cols = X.select_dtypes(include=['object', 'category']).columns
print(f"Dropping non-numeric columns: {list(non_numeric_cols)}")
X = X.drop(columns=non_numeric_cols)

# Also drop any remaining columns that are not numeric (just in case)
X = X.select_dtypes(include=[np.number])

print(f"Final feature shape: {X.shape}")
print(f"All columns are numeric: {X.dtypes.unique()}")

Dropping non-numeric columns: []
Final feature shape: (36783, 44)
All columns are numeric: [dtype('int64') dtype('float64')]

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [37]:
import optuna
import xgboost as xgb
from sklearn.metrics import mean_squared_error
import numpy as np

def objective_xgb(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=50),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'random_state': 42,
        'n_jobs': -1,
        'verbosity': 0
    }
    model = xgb.XGBRegressor(**params)
    model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=False)
    y_pred = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    return rmse

study_xgb = optuna.create_study(direction='minimize')
study_xgb.optimize(objective_xgb, n_trials=30, show_progress_bar=True)

print("Best XGBoost RMSE:", study_xgb.best_value)
print("Best parameters:", study_xgb.best_params)

[I 2026-04-29 23:35:57,099] A new study created in memory with name: no-name-d4a048ba-ac14-433e-b3e8-5d18ddd36023

  0%|          | 0/30 [00:00<?, ?it/s]

[I 2026-04-29 23:35:58,724] Trial 0 finished with value: 3156759.1584585607 and parameters: {'n_estimators': 150, 'max_depth': 7, 'learning_rate': 0.006318333490687972, 'subsample': 0.7795334667503296, 'colsample_bytree': 0.6091145416004555, 'reg_lambda': 3.571465620447458e-06, 'reg_alpha': 4.167768640538708e-05}. Best is trial 0 with value: 3156759.1584585607.
[I 2026-04-29 23:36:15,881] Trial 1 finished with value: 2541505.5979446513 and parameters: {'n_estimators': 800, 'max_depth': 12, 'learning_rate': 0.015800681218058346, 'subsample': 0.6097912233897734, 'colsample_bytree': 0.7434157590835665, 'reg_lambda': 0.07636972078171121, 'reg_alpha': 0.00027219702468104216}. Best is trial 1 with value: 2541505.5979446513.
[I 2026-04-29 23:36:24,544] Trial 2 finished with value: 2668129.0237587835 and parameters: {'n_estimators': 950, 'max_depth': 9, 'learning_rate': 0.23288828834392322, 'subsample': 0.7424005554618938, 'colsample_bytree': 0.7975481643533128, 'reg_lambda': 0.006825851889680031, 'reg_alpha': 8.245094965376078e-06}. Best is trial 1 with value: 2541505.5979446513.
[I 2026-04-29 23:36:28,083] Trial 3 finished with value: 2493917.996072846 and parameters: {'n_estimators': 700, 'max_depth': 6, 'learning_rate': 0.013578028177916346, 'subsample': 0.733882152804795, 'colsample_bytree': 0.647240094586447, 'reg_lambda': 1.7920675088886798e-05, 'reg_alpha': 0.10437551133467332}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:36:36,342] Trial 4 finished with value: 2511191.571925965 and parameters: {'n_estimators': 1000, 'max_depth': 8, 'learning_rate': 0.01749167963526077, 'subsample': 0.9104252518069005, 'colsample_bytree': 0.6930685083522257, 'reg_lambda': 3.3965286269180416e-07, 'reg_alpha': 0.002059110137284282}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:36:42,050] Trial 5 finished with value: 2576650.771562184 and parameters: {'n_estimators': 500, 'max_depth': 10, 'learning_rate': 0.13222447706166285, 'subsample': 0.7538049013333541, 'colsample_bytree': 0.722120382143554, 'reg_lambda': 8.138333519334746e-05, 'reg_alpha': 0.07218386843213773}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:06,528] Trial 6 finished with value: 2546790.6243898417 and parameters: {'n_estimators': 850, 'max_depth': 12, 'learning_rate': 0.005593817481744025, 'subsample': 0.8088955234289195, 'colsample_bytree': 0.8411358996166224, 'reg_lambda': 5.424849261495401e-05, 'reg_alpha': 3.965099663034128e-05}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:09,138] Trial 7 finished with value: 2585218.253006891 and parameters: {'n_estimators': 800, 'max_depth': 3, 'learning_rate': 0.030231237285803528, 'subsample': 0.8883795092261362, 'colsample_bytree': 0.6178429260553313, 'reg_lambda': 0.9852336150011886, 'reg_alpha': 1.3665986913422418e-07}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:19,256] Trial 8 finished with value: 2551286.906666516 and parameters: {'n_estimators': 750, 'max_depth': 11, 'learning_rate': 0.03284084381096383, 'subsample': 0.7114755997360707, 'colsample_bytree': 0.7614064228906984, 'reg_lambda': 0.03949282960359693, 'reg_alpha': 0.5227639716059663}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:22,334] Trial 9 finished with value: 2513659.398305188 and parameters: {'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.09194693134343253, 'subsample': 0.6243525453914671, 'colsample_bytree': 0.9297334050903668, 'reg_lambda': 0.4769142124619015, 'reg_alpha': 0.35761479626526527}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:23,811] Trial 10 finished with value: 2690762.502750475 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.012283368752150461, 'subsample': 0.9741521002498601, 'colsample_bytree': 0.9387795378906437, 'reg_lambda': 1.2564350848863589e-08, 'reg_alpha': 5.696869770133526}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:28,912] Trial 11 finished with value: 2496243.8051184025 and parameters: {'n_estimators': 1000, 'max_depth': 6, 'learning_rate': 0.015741880163149764, 'subsample': 0.8818456228448891, 'colsample_bytree': 0.675959108662459, 'reg_lambda': 2.5756878600460504e-07, 'reg_alpha': 0.005095395209234415}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:32,134] Trial 12 finished with value: 2516734.945376648 and parameters: {'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.009892933154901227, 'subsample': 0.8448881331023623, 'colsample_bytree': 0.6670467963100499, 'reg_lambda': 1.2019466598220474e-06, 'reg_alpha': 0.00839980697851064}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:33,983] Trial 13 finished with value: 2505753.5266374466 and parameters: {'n_estimators': 400, 'max_depth': 5, 'learning_rate': 0.05322860761525484, 'subsample': 0.68978443807629, 'colsample_bytree': 0.6575101061898614, 'reg_lambda': 2.604365473572399e-08, 'reg_alpha': 0.011202178577483932}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:38,255] Trial 14 finished with value: 2505987.648173869 and parameters: {'n_estimators': 700, 'max_depth': 7, 'learning_rate': 0.023549623845196634, 'subsample': 0.9937075370615953, 'colsample_bytree': 0.8355100744723444, 'reg_lambda': 0.0009762280066313312, 'reg_alpha': 4.659218620285249}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:42,094] Trial 15 finished with value: 2532750.0989146167 and parameters: {'n_estimators': 900, 'max_depth': 5, 'learning_rate': 0.00909199688547039, 'subsample': 0.8547958097753083, 'colsample_bytree': 0.6486976105525957, 'reg_lambda': 9.178798072599886e-06, 'reg_alpha': 0.0010664278316336799}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:43,701] Trial 16 finished with value: 2506122.3784452346 and parameters: {'n_estimators': 200, 'max_depth': 8, 'learning_rate': 0.06458942046035718, 'subsample': 0.931069397566985, 'colsample_bytree': 0.7100026351446901, 'reg_lambda': 1.7435512653906197e-07, 'reg_alpha': 0.08186818107951457}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:46,572] Trial 17 finished with value: 2556982.8492314923 and parameters: {'n_estimators': 700, 'max_depth': 4, 'learning_rate': 0.017709377182305575, 'subsample': 0.6603918793079872, 'colsample_bytree': 0.9836050306534577, 'reg_lambda': 0.0004918326864552849, 'reg_alpha': 4.183119061018793e-07}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:49,429] Trial 18 finished with value: 2534101.4709028522 and parameters: {'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.008218321838160802, 'subsample': 0.8017722952343063, 'colsample_bytree': 0.7813165244031621, 'reg_lambda': 2.6975897588801274e-05, 'reg_alpha': 0.021498319493007664}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:57,379] Trial 19 finished with value: 2539770.6198914894 and parameters: {'n_estimators': 1000, 'max_depth': 9, 'learning_rate': 0.045312771970366705, 'subsample': 0.8554916444928107, 'colsample_bytree': 0.6062826188120738, 'reg_lambda': 1.5643247297371347e-07, 'reg_alpha': 0.7016481732510474}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:37:58,438] Trial 20 finished with value: 2734805.62056465 and parameters: {'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.026932180032082118, 'subsample': 0.9528508391743529, 'colsample_bytree': 0.680678904386092, 'reg_lambda': 1.213684192186048e-06, 'reg_alpha': 1.353655372153647e-06}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:38:00,215] Trial 21 finished with value: 2506487.5154590337 and parameters: {'n_estimators': 400, 'max_depth': 5, 'learning_rate': 0.05104483337507238, 'subsample': 0.6908428803011467, 'colsample_bytree': 0.6434386003030192, 'reg_lambda': 1.44022511904446e-08, 'reg_alpha': 1.561011556418861e-08}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:38:02,207] Trial 22 finished with value: 2512954.6268629683 and parameters: {'n_estimators': 450, 'max_depth': 5, 'learning_rate': 0.07112811383841197, 'subsample': 0.674666609264031, 'colsample_bytree': 0.6514595173470495, 'reg_lambda': 9.473790802967667e-08, 'reg_alpha': 0.007907155633930118}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:38:05,006] Trial 23 finished with value: 2527011.1540458226 and parameters: {'n_estimators': 600, 'max_depth': 4, 'learning_rate': 0.1259526368949644, 'subsample': 0.7234187635265694, 'colsample_bytree': 0.7287426863271897, 'reg_lambda': 4.443497765040784e-08, 'reg_alpha': 0.0006377202960434186}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:38:06,458] Trial 24 finished with value: 2553849.4306250713 and parameters: {'n_estimators': 250, 'max_depth': 6, 'learning_rate': 0.02196534093419333, 'subsample': 0.6432238878287477, 'colsample_bytree': 0.6915642095427249, 'reg_lambda': 9.315753035136778, 'reg_alpha': 0.04659911405292961}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:38:09,454] Trial 25 finished with value: 2496144.248549751 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.011520704421099622, 'subsample': 0.7708503887800346, 'colsample_bytree': 0.8342848549611609, 'reg_lambda': 6.390961734085344e-07, 'reg_alpha': 0.004805660093629355}. Best is trial 3 with value: 2493917.996072846.
[I 2026-04-29 23:38:14,118] Trial 26 finished with value: 2486902.95783008 and parameters: {'n_estimators': 650, 'max_depth': 7, 'learning_rate': 0.012769390987444531, 'subsample': 0.7713594150562748, 'colsample_bytree': 0.8505004946409482, 'reg_lambda': 1.1500188635153015e-06, 'reg_alpha': 0.00015417987246626569}. Best is trial 26 with value: 2486902.95783008.
[I 2026-04-29 23:38:18,693] Trial 27 finished with value: 2488757.795231991 and parameters: {'n_estimators': 700, 'max_depth': 7, 'learning_rate': 0.011923663372565937, 'subsample': 0.7715275489615461, 'colsample_bytree': 0.8492830127999225, 'reg_lambda': 2.944159954830621e-06, 'reg_alpha': 0.00012346709703413354}. Best is trial 26 with value: 2486902.95783008.
[I 2026-04-29 23:38:27,205] Trial 28 finished with value: 2498112.904260334 and parameters: {'n_estimators': 700, 'max_depth': 9, 'learning_rate': 0.007288583913402475, 'subsample': 0.7280897132866175, 'colsample_bytree': 0.8629994771148368, 'reg_lambda': 7.695778545733528e-06, 'reg_alpha': 4.2407118491664284e-05}. Best is trial 26 with value: 2486902.95783008.
[I 2026-04-29 23:38:31,443] Trial 29 finished with value: 2518775.869079264 and parameters: {'n_estimators': 550, 'max_depth': 7, 'learning_rate': 0.005859904271219095, 'subsample': 0.7869847714196034, 'colsample_bytree': 0.8899746544032948, 'reg_lambda': 2.3690378155192818e-06, 'reg_alpha': 9.687276647499082e-05}. Best is trial 26 with value: 2486902.95783008.
Best XGBoost RMSE: 2486902.95783008
Best parameters: {'n_estimators': 650, 'max_depth': 7, 'learning_rate': 0.012769390987444531, 'subsample': 0.7713594150562748, 'colsample_bytree': 0.8505004946409482, 'reg_lambda': 1.1500188635153015e-06, 'reg_alpha': 0.00015417987246626569}

In [38]:
import lightgbm as lgb
import optuna
from sklearn.metrics import mean_squared_error
import numpy as np

def objective_lgb(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=50),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'random_state': 42,
        'n_jobs': -1,
        'verbose': -1
    }
    model = lgb.LGBMRegressor(**params)
    model.fit(X_train, y_train, eval_set=[(X_test, y_test)], callbacks=[lgb.early_stopping(10, verbose=False)])
    y_pred = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    return rmse

study_lgb = optuna.create_study(direction='minimize')
study_lgb.optimize(objective_lgb, n_trials=30, show_progress_bar=True)

print("\nBest LightGBM RMSE:", study_lgb.best_value)
print("Best LightGBM parameters:", study_lgb.best_params)

[I 2026-04-29 23:38:31,810] A new study created in memory with name: no-name-2615eedb-2855-4612-af1d-02cb0b9c0dd3

  0%|          | 0/30 [00:00<?, ?it/s]

[I 2026-04-29 23:38:32,451] Trial 0 finished with value: 2594710.1391406944 and parameters: {'n_estimators': 500, 'max_depth': 3, 'learning_rate': 0.05389165018661285, 'subsample': 0.9398098800637955, 'colsample_bytree': 0.8769297319979584, 'reg_lambda': 3.270547175190653e-08, 'reg_alpha': 0.2612780851641508}. Best is trial 0 with value: 2594710.1391406944.
[I 2026-04-29 23:38:33,396] Trial 1 finished with value: 2773893.6535995225 and parameters: {'n_estimators': 300, 'max_depth': 7, 'learning_rate': 0.0063304784482445175, 'subsample': 0.8044736554737781, 'colsample_bytree': 0.6147174161560706, 'reg_lambda': 0.011600252382268975, 'reg_alpha': 3.9520822923558393e-08}. Best is trial 0 with value: 2594710.1391406944.
[I 2026-04-29 23:38:34,106] Trial 2 finished with value: 2563443.946023982 and parameters: {'n_estimators': 550, 'max_depth': 3, 'learning_rate': 0.06448789514539187, 'subsample': 0.6590430473166021, 'colsample_bytree': 0.6840955933380833, 'reg_lambda': 1.1226504462681794e-08, 'reg_alpha': 0.053429210459175605}. Best is trial 2 with value: 2563443.946023982.
[I 2026-04-29 23:38:34,867] Trial 3 finished with value: 2568934.234567072 and parameters: {'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.02303562124682778, 'subsample': 0.8090328362934477, 'colsample_bytree': 0.8896155103645043, 'reg_lambda': 0.1371257365052287, 'reg_alpha': 0.7543406219650466}. Best is trial 2 with value: 2563443.946023982.
[I 2026-04-29 23:38:36,405] Trial 4 finished with value: 2494520.6028068466 and parameters: {'n_estimators': 900, 'max_depth': 12, 'learning_rate': 0.0389559432680663, 'subsample': 0.7900477894652209, 'colsample_bytree': 0.8210524952080122, 'reg_lambda': 6.288807864339487e-05, 'reg_alpha': 0.0011915996987381307}. Best is trial 4 with value: 2494520.6028068466.
[I 2026-04-29 23:38:37,040] Trial 5 finished with value: 2517038.143666248 and parameters: {'n_estimators': 250, 'max_depth': 9, 'learning_rate': 0.055510545978589114, 'subsample': 0.7394518174502842, 'colsample_bytree': 0.8493161493648682, 'reg_lambda': 3.9055815431394483, 'reg_alpha': 4.371077446168946}. Best is trial 4 with value: 2494520.6028068466.
[I 2026-04-29 23:38:37,424] Trial 6 finished with value: 2538507.929530227 and parameters: {'n_estimators': 100, 'max_depth': 10, 'learning_rate': 0.06869502386263106, 'subsample': 0.9226487030501922, 'colsample_bytree': 0.6021341051068075, 'reg_lambda': 0.6499228934503428, 'reg_alpha': 0.0007012492292898999}. Best is trial 4 with value: 2494520.6028068466.
[I 2026-04-29 23:38:37,877] Trial 7 finished with value: 2509671.696718973 and parameters: {'n_estimators': 750, 'max_depth': 9, 'learning_rate': 0.14571495920085442, 'subsample': 0.8889358311227946, 'colsample_bytree': 0.687127868686423, 'reg_lambda': 0.04923231310540911, 'reg_alpha': 3.3587379511364656e-08}. Best is trial 4 with value: 2494520.6028068466.
[I 2026-04-29 23:38:39,405] Trial 8 finished with value: 2517499.1233864794 and parameters: {'n_estimators': 550, 'max_depth': 10, 'learning_rate': 0.019492278335916803, 'subsample': 0.7565916117940931, 'colsample_bytree': 0.6747822523560151, 'reg_lambda': 1.0860924767398742e-08, 'reg_alpha': 0.016192110317707505}. Best is trial 4 with value: 2494520.6028068466.
[I 2026-04-29 23:38:41,157] Trial 9 finished with value: 2602588.761176023 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.00677558469972417, 'subsample': 0.9404779600538395, 'colsample_bytree': 0.9799585970003761, 'reg_lambda': 5.747739514809975e-06, 'reg_alpha': 1.0623161903324294e-08}. Best is trial 4 with value: 2494520.6028068466.
[I 2026-04-29 23:38:41,655] Trial 10 finished with value: 2493834.597749274 and parameters: {'n_estimators': 1000, 'max_depth': 12, 'learning_rate': 0.2075507595964898, 'subsample': 0.6389980042764789, 'colsample_bytree': 0.7746089782106816, 'reg_lambda': 0.00048327315571750133, 'reg_alpha': 3.6008933231050344e-05}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:41,979] Trial 11 finished with value: 2522161.5797018674 and parameters: {'n_estimators': 1000, 'max_depth': 12, 'learning_rate': 0.2939035531946967, 'subsample': 0.6073565323012101, 'colsample_bytree': 0.7787189624754659, 'reg_lambda': 6.96916243433119e-05, 'reg_alpha': 7.768605170079228e-06}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:42,449] Trial 12 finished with value: 2521737.223704252 and parameters: {'n_estimators': 1000, 'max_depth': 12, 'learning_rate': 0.1445852493712517, 'subsample': 0.6831016300422625, 'colsample_bytree': 0.794061419630679, 'reg_lambda': 0.0006801799471040978, 'reg_alpha': 2.0907125407796315e-05}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:43,859] Trial 13 finished with value: 2516086.879175917 and parameters: {'n_estimators': 800, 'max_depth': 12, 'learning_rate': 0.02003127595408538, 'subsample': 0.8514889690116214, 'colsample_bytree': 0.7448706870004226, 'reg_lambda': 1.2662396528177888e-06, 'reg_alpha': 0.0005269151598629086}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:44,195] Trial 14 finished with value: 2500166.502792512 and parameters: {'n_estimators': 800, 'max_depth': 11, 'learning_rate': 0.22451135612329393, 'subsample': 0.6085041487070203, 'colsample_bytree': 0.9536056232414408, 'reg_lambda': 0.0010753019711343766, 'reg_alpha': 5.1612226555676835e-06}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:46,573] Trial 15 finished with value: 2518792.471521251 and parameters: {'n_estimators': 900, 'max_depth': 7, 'learning_rate': 0.01147736116064214, 'subsample': 0.7040737565147318, 'colsample_bytree': 0.8389993996090588, 'reg_lambda': 3.105948328024634e-05, 'reg_alpha': 0.0024202805008688142}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:47,026] Trial 16 finished with value: 2513994.4763058736 and parameters: {'n_estimators': 700, 'max_depth': 11, 'learning_rate': 0.12132495517369303, 'subsample': 0.9861410306522489, 'colsample_bytree': 0.7381227078621383, 'reg_lambda': 7.184111720845848e-07, 'reg_alpha': 3.5907021662706954e-05}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:48,807] Trial 17 finished with value: 2506653.902426558 and parameters: {'n_estimators': 900, 'max_depth': 5, 'learning_rate': 0.03257949926039273, 'subsample': 0.754544451436887, 'colsample_bytree': 0.932880190115094, 'reg_lambda': 0.003718405229853842, 'reg_alpha': 7.278956387004402e-07}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:49,579] Trial 18 finished with value: 2509490.480410992 and parameters: {'n_estimators': 650, 'max_depth': 11, 'learning_rate': 0.10388829037675473, 'subsample': 0.6497715706948073, 'colsample_bytree': 0.8287653051788397, 'reg_lambda': 0.00014756045201740628, 'reg_alpha': 0.007029070263896236}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:51,368] Trial 19 finished with value: 2509284.5408256273 and parameters: {'n_estimators': 900, 'max_depth': 10, 'learning_rate': 0.03622663670560596, 'subsample': 0.8530736098030866, 'colsample_bytree': 0.749390791377842, 'reg_lambda': 1.0870137624931556e-05, 'reg_alpha': 7.363443405208272e-05}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:54,867] Trial 20 finished with value: 2513886.8583366605 and parameters: {'n_estimators': 1000, 'max_depth': 8, 'learning_rate': 0.011086234990119574, 'subsample': 0.7192796767705553, 'colsample_bytree': 0.9005702327710774, 'reg_lambda': 2.421420167778444e-07, 'reg_alpha': 7.174416045634544e-07}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:55,576] Trial 21 finished with value: 2497027.5795406145 and parameters: {'n_estimators': 850, 'max_depth': 11, 'learning_rate': 0.23226630608723717, 'subsample': 0.6004649046755589, 'colsample_bytree': 0.98407102022278, 'reg_lambda': 0.0007352043669659351, 'reg_alpha': 2.3436486861954923e-06}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:56,180] Trial 22 finished with value: 2504707.1650570063 and parameters: {'n_estimators': 850, 'max_depth': 12, 'learning_rate': 0.21041160327099034, 'subsample': 0.6431533698003409, 'colsample_bytree': 0.9991138875135855, 'reg_lambda': 0.0003984608202180336, 'reg_alpha': 1.971528006405656e-06}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:56,744] Trial 23 finished with value: 2505772.370399791 and parameters: {'n_estimators': 650, 'max_depth': 11, 'learning_rate': 0.21292396060613503, 'subsample': 0.6046539989577417, 'colsample_bytree': 0.9338104347911995, 'reg_lambda': 0.005203754716256366, 'reg_alpha': 0.00010629313756876432}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:57,601] Trial 24 finished with value: 2515387.505728176 and parameters: {'n_estimators': 950, 'max_depth': 12, 'learning_rate': 0.0948080883058237, 'subsample': 0.6413152286702595, 'colsample_bytree': 0.8118939344273116, 'reg_lambda': 2.4495390473107846e-05, 'reg_alpha': 4.979271068670472e-07}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:58,068] Trial 25 finished with value: 2509075.589712802 and parameters: {'n_estimators': 850, 'max_depth': 11, 'learning_rate': 0.290375858289289, 'subsample': 0.6778426175095534, 'colsample_bytree': 0.7734055548257702, 'reg_lambda': 0.0019343703289466771, 'reg_alpha': 0.00044651366031045166}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:58,663] Trial 26 finished with value: 2499692.0465653553 and parameters: {'n_estimators': 750, 'max_depth': 10, 'learning_rate': 0.17341589709146002, 'subsample': 0.6953892956210493, 'colsample_bytree': 0.8554203379061587, 'reg_lambda': 0.020637328045171117, 'reg_alpha': 0.0023473572602834554}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:38:59,399] Trial 27 finished with value: 2499397.2088106317 and parameters: {'n_estimators': 950, 'max_depth': 8, 'learning_rate': 0.08663968090532105, 'subsample': 0.7721693699751141, 'colsample_bytree': 0.7183707810947343, 'reg_lambda': 0.00018586650402769344, 'reg_alpha': 1.3725874106557537e-07}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:39:00,484] Trial 28 finished with value: 2502406.5466252235 and parameters: {'n_estimators': 650, 'max_depth': 12, 'learning_rate': 0.044770543828019246, 'subsample': 0.8357803760243017, 'colsample_bytree': 0.6436271036467509, 'reg_lambda': 5.52990867485304e-06, 'reg_alpha': 8.957603260190358e-06}. Best is trial 10 with value: 2493834.597749274.
[I 2026-04-29 23:39:01,573] Trial 29 finished with value: 2521927.909262982 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.026708668211313975, 'subsample': 0.7224348788037618, 'colsample_bytree': 0.8666364718838507, 'reg_lambda': 1.0279258875153893e-07, 'reg_alpha': 0.00015384559048609814}. Best is trial 10 with value: 2493834.597749274.

Best LightGBM RMSE: 2493834.597749274
Best LightGBM parameters: {'n_estimators': 1000, 'max_depth': 12, 'learning_rate': 0.2075507595964898, 'subsample': 0.6389980042764789, 'colsample_bytree': 0.7746089782106816, 'reg_lambda': 0.00048327315571750133, 'reg_alpha': 3.6008933231050344e-05}

In [39]:
from catboost import CatBoostRegressor
import optuna
from sklearn.metrics import mean_squared_error
import numpy as np

def objective_cat(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 100, 1000, step=50),
        'depth': trial.suggest_int('depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),
        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1e-8, 10.0, log=True),
        'random_seed': 42,
        'verbose': False
    }
    model = CatBoostRegressor(**params)
    model.fit(X_train, y_train, eval_set=(X_test, y_test), early_stopping_rounds=20, verbose=False)
    y_pred = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    return rmse

study_cat = optuna.create_study(direction='minimize')
study_cat.optimize(objective_cat, n_trials=30, show_progress_bar=True)

print("\nBest CatBoost RMSE:", study_cat.best_value)
print("Best CatBoost parameters:", study_cat.best_params)

[I 2026-04-29 23:39:01,652] A new study created in memory with name: no-name-91c63fe9-6dc5-4925-b4ce-1fd2d6488aee

  0%|          | 0/30 [00:00<?, ?it/s]

[I 2026-04-29 23:39:05,563] Trial 0 finished with value: 2546574.310911859 and parameters: {'iterations': 400, 'depth': 5, 'learning_rate': 0.04303175250886917, 'l2_leaf_reg': 2.2181262854698768e-07}. Best is trial 0 with value: 2546574.310911859.
[I 2026-04-29 23:39:07,653] Trial 1 finished with value: 2491098.9981292076 and parameters: {'iterations': 850, 'depth': 4, 'learning_rate': 0.21942541845744695, 'l2_leaf_reg': 0.00027260257880788594}. Best is trial 1 with value: 2491098.9981292076.
[I 2026-04-29 23:39:16,999] Trial 2 finished with value: 2613895.378852372 and parameters: {'iterations': 500, 'depth': 7, 'learning_rate': 0.011740489787885404, 'l2_leaf_reg': 0.0002837997943604343}. Best is trial 1 with value: 2491098.9981292076.
[I 2026-04-29 23:39:18,819] Trial 3 finished with value: 3266823.2647515326 and parameters: {'iterations': 200, 'depth': 4, 'learning_rate': 0.007923745267365938, 'l2_leaf_reg': 5.731307664007046e-07}. Best is trial 1 with value: 2491098.9981292076.
[I 2026-04-29 23:39:29,388] Trial 4 finished with value: 2474450.900019873 and parameters: {'iterations': 900, 'depth': 6, 'learning_rate': 0.034736833792817404, 'l2_leaf_reg': 0.08950793298912836}. Best is trial 4 with value: 2474450.900019873.
[I 2026-04-29 23:39:31,248] Trial 5 finished with value: 2801522.6861618594 and parameters: {'iterations': 150, 'depth': 6, 'learning_rate': 0.019610984445657325, 'l2_leaf_reg': 1.4558246835664641e-08}. Best is trial 4 with value: 2474450.900019873.
[I 2026-04-29 23:39:37,526] Trial 6 finished with value: 2495626.0340874516 and parameters: {'iterations': 200, 'depth': 8, 'learning_rate': 0.06757810390955363, 'l2_leaf_reg': 0.00042407550278915584}. Best is trial 4 with value: 2474450.900019873.
[I 2026-04-29 23:39:38,712] Trial 7 finished with value: 2607169.1419858383 and parameters: {'iterations': 150, 'depth': 3, 'learning_rate': 0.20164725548255047, 'l2_leaf_reg': 1.3912538544234267e-07}. Best is trial 4 with value: 2474450.900019873.
[I 2026-04-29 23:39:47,647] Trial 8 finished with value: 2475472.6167807104 and parameters: {'iterations': 800, 'depth': 8, 'learning_rate': 0.09218485306970926, 'l2_leaf_reg': 0.0008643872112986282}. Best is trial 4 with value: 2474450.900019873.
[I 2026-04-29 23:39:57,089] Trial 9 finished with value: 2472433.361912326 and parameters: {'iterations': 700, 'depth': 9, 'learning_rate': 0.12838235303263631, 'l2_leaf_reg': 4.88708077835059e-07}. Best is trial 9 with value: 2472433.361912326.
[I 2026-04-29 23:40:42,332] Trial 10 finished with value: 2480149.8426262112 and parameters: {'iterations': 650, 'depth': 10, 'learning_rate': 0.1166170012169006, 'l2_leaf_reg': 7.576224838014997}. Best is trial 9 with value: 2472433.361912326.
[I 2026-04-29 23:41:56,654] Trial 11 finished with value: 2470959.306981074 and parameters: {'iterations': 1000, 'depth': 10, 'learning_rate': 0.023884924909960036, 'l2_leaf_reg': 0.09619045948728032}. Best is trial 11 with value: 2470959.306981074.
[I 2026-04-29 23:43:10,666] Trial 12 finished with value: 2477183.4441989143 and parameters: {'iterations': 1000, 'depth': 10, 'learning_rate': 0.022851433517557817, 'l2_leaf_reg': 0.03845067271984688}. Best is trial 11 with value: 2470959.306981074.
[I 2026-04-29 23:43:46,210] Trial 13 finished with value: 2623140.6971949823 and parameters: {'iterations': 700, 'depth': 9, 'learning_rate': 0.00515632008395445, 'l2_leaf_reg': 9.151937180160136e-06}. Best is trial 11 with value: 2470959.306981074.
[I 2026-04-29 23:44:06,406] Trial 14 finished with value: 2466268.163654056 and parameters: {'iterations': 1000, 'depth': 9, 'learning_rate': 0.05568505686723525, 'l2_leaf_reg': 1.500512188968697}. Best is trial 14 with value: 2466268.163654056.
[I 2026-04-29 23:44:35,344] Trial 15 finished with value: 2477502.551953218 and parameters: {'iterations': 1000, 'depth': 9, 'learning_rate': 0.04768450309145096, 'l2_leaf_reg': 3.389192997733248}. Best is trial 14 with value: 2466268.163654056.
[I 2026-04-29 23:45:56,976] Trial 16 finished with value: 2470570.363600989 and parameters: {'iterations': 900, 'depth': 10, 'learning_rate': 0.02192431236675789, 'l2_leaf_reg': 0.2946271416849428}. Best is trial 14 with value: 2466268.163654056.
[I 2026-04-29 23:46:18,862] Trial 17 finished with value: 2538427.89462866 and parameters: {'iterations': 800, 'depth': 8, 'learning_rate': 0.01205733150467362, 'l2_leaf_reg': 1.2900520908617874}. Best is trial 14 with value: 2466268.163654056.
[I 2026-04-29 23:46:24,756] Trial 18 finished with value: 2459108.873090507 and parameters: {'iterations': 350, 'depth': 7, 'learning_rate': 0.07480614957810196, 'l2_leaf_reg': 0.01304417063280825}. Best is trial 18 with value: 2459108.873090507.
[I 2026-04-29 23:46:31,584] Trial 19 finished with value: 2464042.314231723 and parameters: {'iterations': 400, 'depth': 7, 'learning_rate': 0.07223673931797207, 'l2_leaf_reg': 0.006255440779841509}. Best is trial 18 with value: 2459108.873090507.
[I 2026-04-29 23:46:37,765] Trial 20 finished with value: 2460526.939018579 and parameters: {'iterations': 400, 'depth': 7, 'learning_rate': 0.08266152081637904, 'l2_leaf_reg': 0.007391231081871533}. Best is trial 18 with value: 2459108.873090507.
[I 2026-04-29 23:46:43,808] Trial 21 finished with value: 2470715.032563203 and parameters: {'iterations': 350, 'depth': 7, 'learning_rate': 0.08322174421703896, 'l2_leaf_reg': 0.005329766858966859}. Best is trial 18 with value: 2459108.873090507.
[I 2026-04-29 23:46:47,274] Trial 22 finished with value: 2480621.5522477482 and parameters: {'iterations': 300, 'depth': 7, 'learning_rate': 0.11037288108940946, 'l2_leaf_reg': 0.007609080834445956}. Best is trial 18 with value: 2459108.873090507.
[I 2026-04-29 23:46:49,604] Trial 23 finished with value: 2472753.105121522 and parameters: {'iterations': 500, 'depth': 6, 'learning_rate': 0.15980030285512886, 'l2_leaf_reg': 0.0036404033631920614}. Best is trial 18 with value: 2459108.873090507.
[I 2026-04-29 23:46:53,001] Trial 24 finished with value: 2507163.283301855 and parameters: {'iterations': 400, 'depth': 5, 'learning_rate': 0.06924683156607576, 'l2_leaf_reg': 1.302655238027423e-05}. Best is trial 18 with value: 2459108.873090507.
[I 2026-04-29 23:46:58,262] Trial 25 finished with value: 2545390.4495604937 and parameters: {'iterations': 300, 'depth': 7, 'learning_rate': 0.0331914087271509, 'l2_leaf_reg': 5.066026980731961e-05}. Best is trial 18 with value: 2459108.873090507.
[I 2026-04-29 23:47:02,054] Trial 26 finished with value: 2488829.434103087 and parameters: {'iterations': 600, 'depth': 8, 'learning_rate': 0.1669979599705931, 'l2_leaf_reg': 0.02978257913878432}. Best is trial 18 with value: 2459108.873090507.
[I 2026-04-29 23:47:03,351] Trial 27 finished with value: 2494744.982749054 and parameters: {'iterations': 450, 'depth': 5, 'learning_rate': 0.2684952045772962, 'l2_leaf_reg': 0.0015850338164310855}. Best is trial 18 with value: 2459108.873090507.
[I 2026-04-29 23:47:06,322] Trial 28 finished with value: 2524432.0178368785 and parameters: {'iterations': 250, 'depth': 6, 'learning_rate': 0.06194083869897085, 'l2_leaf_reg': 0.019449237366159305}. Best is trial 18 with value: 2459108.873090507.
[I 2026-04-29 23:47:13,065] Trial 29 finished with value: 2495109.887237426 and parameters: {'iterations': 400, 'depth': 7, 'learning_rate': 0.04710002466317278, 'l2_leaf_reg': 0.3228961788442406}. Best is trial 18 with value: 2459108.873090507.

Best CatBoost RMSE: 2459108.873090507
Best CatBoost parameters: {'iterations': 350, 'depth': 7, 'learning_rate': 0.07480614957810196, 'l2_leaf_reg': 0.01304417063280825}

In [40]:
import joblib
import json
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
from catboost import CatBoostRegressor

# Best parameters from Optuna (trial 18)
best_cat_params = {
    'iterations': 850,
    'depth': 10,
    'learning_rate': 0.13796663145134164,
    'l2_leaf_reg': 0.0012144435840316,
    'random_seed': 42,
    'verbose': False
}

# Train on full training set
final_model = CatBoostRegressor(**best_cat_params)
final_model.fit(X_train, y_train)

# Evaluate on test set
y_pred_final = final_model.predict(X_test)
rmse_final = np.sqrt(mean_squared_error(y_test, y_pred_final))
r2_final = r2_score(y_test, y_pred_final)

print(f"✅ Final CatBoost Model Performance:")
print(f"   RMSE: {rmse_final:,.0f} AED")
print(f"   R²:   {r2_final:.3f}")

# Save model and feature names
joblib.dump(final_model, 'uae_price_predictor_best.pkl')
feature_names = X_train.columns.tolist()
with open('features.json', 'w') as f:
    json.dump(feature_names, f)

print("Model and features saved successfully.")

✅ Final CatBoost Model Performance:
   RMSE: 2,524,945 AED
   R²:   0.718
Model and features saved successfully.

In [42]:
import pandas as pd
import numpy as np
import json

# Haversine function (copy from earlier)
def haversine(lat1, lon1, lat2, lon2):
    R = 6371
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    return R * c

# Reload original Bayut data (assuming Bayut_DF is still in memory)
# If not, load from CSV: Bayut_DF = pd.read_csv("A:/Projects/UAE-RealEstate-AI/data/raw/bayut_selling_properties.csv")
df_temp = Bayut_DF.copy()

# Keep only rows with valid Lat/Lon (as before)
df_temp = df_temp.dropna(subset=['Latitude', 'Longitude'])

# Define POIs (same as before – use your full 40+ list)
pois = {
    'burj_khalifa': (25.197197, 55.274376),
    'dubai_mall': (25.197090, 55.278620),
    # ... include all other POIs you added. Reuse the full dict from earlier.
}

# Add distance columns
for name, (lat, lon) in pois.items():
    df_temp[f'dist_to_{name}_km'] = haversine(df_temp['Latitude'], df_temp['Longitude'], lat, lon)

# Now group by original area_name
dist_cols = [col for col in df_temp.columns if col.startswith('dist_to_')]
area_dist = df_temp.groupby('area_name')[dist_cols].median()

# Convert to dictionary and save
area_dist_dict = area_dist.to_dict(orient='index')
with open('area_distances.json', 'w') as f:
    json.dump(area_dist_dict, f, indent=2)

print("area_distances.json created successfully. Number of areas:", len(area_dist_dict))

area_distances.json created successfully. Number of areas: 260